apiVersion : apps/v1
kind : Deployment
metadata : 
  labels : 
    app : node-app-2
  name : node-app-2
spec:
  replicas : 1
  selector :
    matchLabels : 
      app : node-app-2-pod
  template : 
    metadata : 
      labels : 
        app : node-app-2-pod
    spec :
      containers : 
      - name: node-application
        env :
        - name : DB_URI
          value : mongodb://mongodb-service:27017/node-application
        image : sheenam1993/node-application
        ports : 
        - containerPort: 3007
      restartPolicy: Always
      
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-app-2-pod
  name: node-app-2-service
spec:
  ports:
  - port: 8080
    targetPort: 3007
    nodePort: 30009
  selector:
    app: node-app-2-pod
  type: NodePort